Make sure we all use the same version of Antora
I noticed the diff showing a lot of v3.0.0 / v3.0.1 changes. Maybe we
should make sure to always use the same version? Or maybe it doesn't
matter?

The `set -e` also makes sure that we don't push an empty commit in case
the `antora` command fails.

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -1,5 +1,13 @@
 #!/bin/sh
 
+set -e
+
+antora_version='3.0.1'
+if ! antora --version | grep -Fq $antora_version; then
+  echo "Error: Please use Antora v$antora_version"
+  exit 1
+fi
+
 antora --fetch antora-playbook.yml
 git add docs
 git commit -m 'Update site docs'
